# see https://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:

  shell: bash
  parameter-store:
    DOCKERHUB_PASS_PARAM: /dockerhub-access-token-for-pwighton

phases:
  install:
    on-failure: ABORT
    commands:
      - export DOCKERHUB_PASS=$DOCKERHUB_PASS_PARAM
      - docker login --username pwighton --password $DOCKERHUB_PASS
  build:
    on-failure: ABORT
    commands:
      - docker build -t pwighton/neurodocker .
  post_build:
    on-failure: ABORT
    commands:
      - docker push pwighton/neurodocker:latest
